### ISSUE TITLE
AOT compiling breaks projects that use recent tools.reader features

### ISSUE THREAD

**Issue by danielneal** [flexsurfer/lein-re-frisk#2]
Because the project is AOT compiled, it bundles an older version of tools.reader in a way that can not be overridden. 

This breaks any projects that use more recent features of tools.reader, such as clojure 1.9's namespaced map syntax `#foo{:bar 1}`

I've put up a repro demonstrating the problem here: 
https://github.com/danielneal/refrisk-dependency-issue

If the project was not AOT compiled, end users would be able to use `:exclusions` to use their version of tools.reader, but at the moment this is impossible. 

It can be fixed by removing `:main` here (which I've tried and works) 
https://github.com/flexsurfer/lein-re-frisk/blob/master/re-frisk-sidecar/project.clj#L20

Or possibly marking it as `^:skip-aot` but I haven't tried that. 
https://github.com/technomancy/leiningen/blob/master/sample.project.clj#L210-L217

**Comment by flexsurfer** [comment]
thank you @danielneal it's really helpful, i forget to remove `:main`, it was for test purposes :( will do it later today!

**Comment by danielneal** [comment]
Awesome thanks!

**Comment by flexsurfer** [comment]
fixed in 0.5.1, @danielneal  please check, and thanks :)
